export default {
  USE_YN: [
    { name: 'Y', value: 'Y' },
    { name: 'N', value: 'N' },
  ],
  DISP_YN: [
    { name: 'Y', value: 'Y' },
    { name: 'N', value: 'N' },
  ],
  CRUD_CTRL_YN: [
    { name: 'Y', value: 'Y' },
    { name: 'N', value: 'N' },
  ],
  SCREEN_TP: [
    { value: 'MAIN', name: '메인화면' },
    { value: 'DASHBAORD', name: 'DashBoard' },
  ],
  DATA_AUTH: [
    { value: '-1', name: '처리안함' },
    { value: '100', name: '본인자료' },
    { value: '200', name: '본인부서자료' },
    { value: '300', name: '상위부서자료' },
    { value: '400', name: '사용자정의 부서그룹' },
    { value: '0', name: '전체' },
  ],
  SYS_DV: [
    { value: 'CMG', name: '공통' },
    { value: 'PAL', name: '생산물류' },
    { value: 'SEI', name: '서비스교육' },
    { value: 'SAM', name: '영업마케팅' },
  ],
  TASK_CD: [
    { link: 'CMG', value: 'CIF', name: '업무공통 인터페이스' },
    { link: 'CMG', value: 'COM', name: '업무공통' },
    { link: 'CMG', value: 'OXF', name: '프레임워크' },
    { link: 'CMG', value: 'EAP', name: '전자결재' },
    { link: 'CMG', value: 'TSK', name: '할일관리' },
    { link: 'PAL', value: 'LIF', name: '생산물류 인터페이스' },
    { link: 'PAL', value: 'LCM', name: '생산물류 공통' },
    { link: 'PAL', value: 'LOG', name: '생산물류 업무처리' },
    { link: 'PAL', value: 'PAT', name: '협력사 포털' },
    { link: 'PAL', value: 'MAL', name: '이커머스' },
    { link: 'PAL', value: 'MEM', name: '통합회원관리' },
    { link: 'SEI', value: 'EIF', name: '서비스교육 인터페이스' },
    { link: 'SEI', value: 'SVC', name: '서비스' },
    { link: 'SEI', value: 'OIC', name: '교육' },
    { link: 'SEI', value: 'INT', name: '인테리어' },
    { link: 'SEI', value: 'JOB', name: '덴잡' },
    { link: 'SAM', value: 'SIF', name: '영업마케팅 인터페이스' },
    { link: 'SAM', value: 'SAL', name: '국내영업' },
  ],
  DTY_CD: [
    { value: '002', name: '회장' },
    { value: '003', name: '대표이사' },
    { value: '010', name: '등기임원' },
    { value: '020', name: '임원' },
    { value: '025', name: '부문장' },
    { value: '026', name: '센터장' },
    { value: '030', name: '본부장' },
    { value: '031', name: '본부장(지역)' },
    { value: '0313', name: '단장' },
    { value: '032', name: '총괄본부장' },
    { value: '036', name: '부장' },
    { value: '040', name: '연구소장' },
    { value: '041', name: '원장' },
    { value: '050', name: '실장' },
    { value: '052', name: '전문위원' },
    { value: '053', name: 'Marketing Director' },
    { value: '054', name: 'Manager' },
    { value: '055', name: 'Associate' },
    { value: '057', name: 'Supervisor' },
    { value: '080', name: '고문' },
    { value: '085', name: '자문' },
    { value: '100', name: '부서장' },
    { value: '110', name: '팀장' },
    { value: '111', name: '부팀장' },
    { value: '114', name: '유럽법인장' },
    { value: '115', name: '법인장' },
    { value: '116', name: '법인장대행' },
    { value: '117', name: '부법인장' },
    { value: '118', name: '총괄법인장' },
    { value: '120', name: '소장' },
    { value: '125', name: '지점장' },
    { value: '127', name: '부지점장' },
    { value: '200', name: '부서장대행' },
    { value: '210', name: '팀장대행' },
    { value: '220', name: '소장대행' },
    { value: '230', name: '조장' },
    { value: '300', name: '팀장(제조)' },
    { value: '301', name: '파트장' },
    { value: '302', name: '파트장대행' },
    { value: '310', name: '팀장(파트장)' },
    { value: '320', name: '반장' },
    { value: '330', name: '반장대행' },
    { value: '400', name: '팀원' },
    { value: '410', name: '팀원(제조)' },
    { value: '420', name: '간사' },
    { value: '500', name: '별정직' },
    { value: '600', name: '계약직' },
    { value: '700', name: '실습생' },
    { value: '800', name: '임시코드(병특)' },
  ],
  TO_ROLE: [
    { value: '0', name: '없음' },
    { value: '1', name: '만' },
    { value: '2', name: '이상' },
    { value: '3', name: '까지' },
    { value: '4', name: '사이' },
  ],
  USER_STAT_CD: [
    { value: '20', name: '재직' },
    { value: '90', name: '퇴직' },
  ],
  USER_SEARCH_KEY: [
    { value: '1', name: '이름' },
    { value: '2', name: '사번' },
    { value: '3', name: '전화번호' },
    { value: '4', name: '이메일' },
  ],
  SCREEN_LAYOUT: [
    { name: '', value: 0, scrnRto: [] },
    { name: '라디오1', value: 1, scrnRto: [100], path: 'dashboard_1.png' },
    { name: '라디오2', value: 2, scrnRto: [50, 50], path: 'dashboard_2.png' },
    { name: '라디오3', value: 3, scrnRto: [50, 50, 100], path: 'dashboard_3.png' },
    { name: '라디오4', value: 4, scrnRto: [100, 100], path: 'dashboard_4.png' },
    { name: '라디오5', value: 5, scrnRto: [100, 50, 50], path: 'dashboard_5.png' },
    { name: '라디오6', value: 6, scrnRto: [50, 50, 50, 50], path: 'dashboard_6.png' },
    { name: '라디오7', value: 7, scrnRto: [33, 33, 33, 33, 33, 33], path: 'dashboard_7.png' },
    { name: '라디오8', value: 8, scrnRto: [50, 50, 33, 33, 33], path: 'dashboard_8.png' },
    { name: '라디오9', value: 9, scrnRto: [33, 33, 33, 50, 50], path: 'dashboard_9.png' },
    { name: '라디오10', value: 10, scrnRto: [100, 33, 33, 33], path: 'dashboard_10.png' },
    { name: '라디오11', value: 11, scrnRto: [33, 33, 33, 100], path: 'dashboard_11.png' },
  ],
};