export default {
    USE_YN: [
        { name: 'Y', value: 'Y' },
        { name: 'N', value: 'N' },
    ],
    SYS_DV: [
        { value: 'CMG', name: '공통' },
        { value: 'PAL', name: '생산물류' },
        { value: 'SEI', name: '서비스교육' },
        { value: 'SAM', name: '영업마케팅' },
    ],
    TASK_CD: [
        { link: 'CMG', value: 'CIF', name: '업무공통 인터페이스' },
        { link: 'CMG', value: 'COM', name: '업무공통' },
        { link: 'CMG', value: 'OXF', name: '프레임워크' },
        { link: 'CMG', value: 'EAP', name: '전자결재' },
        { link: 'CMG', value: 'TSK', name: '할일관리' },
        { link: 'PAL', value: 'LIF', name: '생산물류 인터페이스' },
        { link: 'PAL', value: 'LCM', name: '생산물류 공통' },
        { link: 'PAL', value: 'LOG', name: '생산물류 업무처리' },
        { link: 'PAL', value: 'PAT', name: '협력사 포털' },
        { link: 'PAL', value: 'MAL', name: '이커머스' },
        { link: 'PAL', value: 'MEM', name: '통합회원관리' },
        { link: 'SEI', value: 'EIF', name: '서비스교육 인터페이스' },
        { link: 'SEI', value: 'SVC', name: '서비스' },
        { link: 'SEI', value: 'OIC', name: '교육' },
        { link: 'SEI', value: 'INT', name: '인테리어' },
        { link: 'SEI', value: 'JOB', name: '덴잡' },
        { link: 'SAM', value: 'SIF', name: '영업마케팅 인터페이스' },
        { link: 'SAM', value: 'SAL', name: '국내영업' },
    ],
};